openapi: 3.0.3
info:
  title: API de consultório
  description: API para controlar médicos e suas especialidades dentro do consultório
  version: 1.0.0
  termsOfService: https://mockapi.io
  contact:
    name: Suporte a Devs
    email: contato@example.com
    url: https://mockapi.io
  license:
    name: "Licença: GPLv3"
    url: https://www.gnu.org/licences/gpl-3.0.html
externalDocs:
  description: Documentação burocrática
  url: https://mockapi.io
servers:
  - url: https://6096015d116f3f00174b29ba.mockapi.io/
    description: API de Teste
paths:
  /especialidades:
    get:
      tags:
        - especialidades
      summary: Recupera todas as especialidades
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Especialidade"
    post:
      tags:
        - especialidades
      summary: Cria nova especialidade
      description: Através desse endpoint você pode criar novas especialidades
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
      responses:
        "201":
          $ref: "#/components/responses/Sucesso"
  /especialidades/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    get:
      tags:
        - especialidades
      summary: Recupera uma entidade pelo id
      responses:
        200:
          $ref: "#/components/responses/Sucesso"
        404:
          description: especialidade não encontrada
          content:
            application/json:
              example: "Not found"
    put:
      tags:
        - especialidades
      summary: Atualiza uma entidade por id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Especialidade"
      responses:
        "200":
          $ref: "#/components/responses/Sucesso"
    delete:
      tags:
        - especialidades
      summary: Atualiza uma entidade por id
      responses:
        "200":
          $ref: "#/components/responses/Sucesso"
security:
  - auth: []
components:
  schemas:
    Especialidade:
      type: object
      properties:
        id:
          type: integer
        descricao:
          type: string
  responses:
    Sucesso:
      description: Sucesso
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Especialidade"
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
